name: memogenerator
description: An app to generate memes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.1.4
flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    # - assets/images/
    # - .env
